stages:
    - unit-testing
    - integration-testing
    - release

unit-testing:
  stage: unit-testing
  image: python:3.8-stretch
  script:
    - echo "Install dependencies"
    - apt-get update
    - apt-get install default-jdk -y
    - pip install -e ".[local,test]"
    - echo "Launching unit tests"
    - pytest tests/unit

integration-testing:
  stage: integration-testing
  image: python:3.7-stretch
  script:
    - echo "Install dependencies"
    - pip install -e ".[local,test]"
    - echo "Deploying tests"
    - dbx deploy {{project_name}}-sample-etl --assets-only
    - echo "Running tests"
    - dbx launch {{project_name}}-sample-etl --from-assets --trace

release:
  stage: release
  image: python:3.7-stretch
  only:
    refs:
      - master
  script:
    - echo "Install dependencies"
    - pip install -e ".[local,test]"
    - echo "Deploying Job"
    - dbx deploy {{project_name}}-sample-etl
